import { Aggettivo, Nome } from "@/lib/types";

const nomi: Nome[] = [
  { nome: "Quokka", genere: "maschile" },
  { nome: "Cervo", genere: "maschile" },
  { nome: "Capriolo", genere: "maschile" },
  { nome: "Daino", genere: "maschile" },
  { nome: "Cinghiale", genere: "maschile" },
  { nome: "Fagiano", genere: "maschile" },
  { nome: "Lepre", genere: "femminile" },
  { nome: "Faina", genere: "femminile" },
  { nome: "Volpe", genere: "maschile" },
  { nome: "Tasso", genere: "maschile" },
  { nome: "Cane", genere: "maschile" },
  { nome: "Gatto", genere: "maschile" },
  { nome: "Cavallo", genere: "maschile" },
  { nome: "Pecora", genere: "femminile" },
  { nome: "Mucca", genere: "femminile" },
  { nome: "Toro", genere: "maschile" },
  { nome: "Aquila", genere: "femminile" },
  { nome: "Gufo", genere: "maschile" },
  { nome: "Lupo", genere: "maschile" },
  { nome: "Orso", genere: "maschile" },
  { nome: "Scoiattolo", genere: "maschile" },
  { nome: "Cigno", genere: "maschile" },
  { nome: "Pavone", genere: "maschile" },
  { nome: "Giraffa", genere: "femminile" },
  { nome: "Elefante", genere: "maschile" },
  { nome: "Vento", genere: "maschile" },
  { nome: "Quercia", genere: "femminile" },
  { nome: "Ruscello", genere: "maschile" },
  { nome: "Montagna", genere: "femminile" },
  { nome: "Fiume", genere: "maschile" },
  { nome: "Lago", genere: "maschile" },
  { nome: "Mare", genere: "maschile" },
  { nome: "Foresta", genere: "femminile" },
  { nome: "Bosco", genere: "maschile" },
  { nome: "Prato", genere: "maschile" },
  { nome: "Fiore", genere: "maschile" },
  { nome: "Albero", genere: "maschile" },
  { nome: "Roccia", genere: "femminile" },
  { nome: "Sole", genere: "maschile" },
  { nome: "Luna", genere: "femminile" },
  { nome: "Stella", genere: "femminile" },
  { nome: "Nebbia", genere: "femminile" },
  { nome: "Pioggia", genere: "femminile" },
  { nome: "Neve", genere: "femminile" },
  { nome: "Tempesta", genere: "femminile" },
];

const aggettivi: Aggettivo[] = [
  { maschile: "Premuroso", femminile: "Premurosa" },
  "Forte",
  { maschile: "Timido", femminile: "Timida" },
  "Veloce",
  { maschile: "Astuto", femminile: "Astuta" },
  { maschile: "Coraggioso", femminile: "Coraggiosa" },
  "Fedele",
  { maschile: "Furbo", femminile: "Furba" },
  { maschile: "Rapido", femminile: "Rapida" },
  "Intelligente",
  "Leale",
  { maschile: "Saggio", femminile: "Saggia" },
  { maschile: "Silenzioso", femminile: "Silenziosa" },
  "Vivace",
  "Gentile",
  { maschile: "Affettuoso", femminile: "Affettuosa" },
  "Elegante",
  { maschile: "Energico", femminile: "Energica" },
  "Dolce",
  { maschile: "Curioso", femminile: "Curiosa" },
  "Sensibile",
  { maschile: "Simpatico", femminile: "Simpatica" },
  { maschile: "Giocherellone", femminile: "Giocherellona" },
  { maschile: "Testardo", femminile: "Testarda" },
  { maschile: "Rilassato", femminile: "Rilassata" },
  { maschile: "Avventuroso", femminile: "Avventurosa" },
  "Affidabile",
  "Amichevole",
  { maschile: "Creativo", femminile: "Creativa" },
  { maschile: "Determinato", femminile: "Determinata" },
  { maschile: "Generoso", femminile: "Generosa" },
  { maschile: "Grintoso", femminile: "Grintosa" },
  "Ottimista",
  "Paziente",
  "Prudente",
  { maschile: "Rispettoso", femminile: "Rispettosa" },
  "Socievole",
  { maschile: "Spontaneo", femminile: "Spontanea" },
  "Tenace",
  "Versatile",
];

export default function generaNomeDiCaccia() {
  const nome = nomi[Math.floor(Math.random() * nomi.length)];
  const aggettivo = aggettivi[Math.floor(Math.random() * aggettivi.length)];
  if (typeof aggettivo === "string") {
    return `${nome.nome} ${aggettivo}`;
  }
  return `${nome.nome} ${aggettivo[nome.genere]}`;
}
